"""Revised actual Paper3 v5, sourced from the supplied v4 + strict authorities."""
import argparse,subprocess
from common05 import *
from report05 import select,decision,LIMITATION
def esc(s):
    return str(s).replace('\\',r'\textbackslash{}').replace('&',r'\&').replace('%',r'\%').replace('_',r'\_').replace('#',r'\#').replace('|',r'\,|\,')
def num(x):return f'{float(x):.7g}'
def pct(rr,k='relative_effect'):return ', '.join(f"{100*float(r[k]):.2f}\\%" for r in rr)
def table(caption,head,rows):
    return '\n\\begin{center}\\small\n'+r'\begin{longtable}{'+'l'+'r'*(len(head)-1)+'}\n\\caption{'+caption+'}\\\\\n\\toprule\n'+' & '.join(head)+r' \\ \midrule'+'\n'+'\n'.join(' & '.join(esc(x) for x in row)+r' \\' for row in rows)+'\n\\bottomrule\n\\end{longtable}\n\\end{center}\n'
def fig(n,caption):return '\n\\begin{figure}[p]\n\\centering\n\\includegraphics[width=\\textwidth]{figure'+f'{n:02}'+'.pdf}\n\\caption{'+caption+'}\n\\label{fig:'+str(n)+'}\n\\end{figure}\n'
def build():
    freeze();revealed();original=(ROOT/'manuscript_authority/Paper3_v4_original.tex').read_text();preamble=original.split(r'\begin{document}')[0].replace(r'\graphicspath{{figures/}}',r'\graphicspath{{../figures/}}');intro=original.split(r'\section{Introduction}',1)[1].split(r'\section{Results}',1)[0];defs=original.split(r'\subsection{Finite relational geometry}',1)[1].split(r'\subsection{Construction guarantees}',1)[0];admin=original.split(r'\section{Author contributions}',1)[1].split(r'\appendix',1)[0];admin=admin.split(r'\section{Final within-carrier conditional inference map}')[0];bib=original[original.index(r'\begin{thebibliography}'):original.index(r'\end{thebibliography}')+len(r'\end{thebibliography}')]
    ee=select('edge_agreement');co=select('matched_coherence/q25','heldout','defect');fi=select('source_fidelity/q25','heldout','source_error');sc=select('matched_coherence/q25','state','defect');sf=select('source_fidelity/q25','state','source_error');spatial=select('spatial_overlap/S1');sampler=read(ROOT/'source_fidelity/sampler_transparency.csv');fid=decision('source_fidelity/q25','heldout','source_error')
    s=preamble+r'''\begin{document}
\maketitle
\begin{center}\small
\copyright\ 2026 Zed James. This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.

\textbf{Preprint draft v5 --- October 4, 2026. Strict feature-separation revision.}
\end{center}
\begin{abstract}
Developmental molecular measurements support local relations without necessarily defining a unique finite biological identity. We analyze 3,704 lineage-qualified cells from three E7.5 mouse embryos through embryo carriers, pair-local relations, source domains, set-valued target fibers and source-domain overlaps. The publication-primary relation is reconstructed from nine state lanes whose complete gene union is contained in a frozen 14,660-gene state panel and disjoint from a 6,339-gene molecular evaluation panel. Each lane uses its own selected-gene size factor. Geometry is committed before molecular evaluation. Historical partially overlapping alternate panels are retained only as sensitivity provenance, not as held-out primary evidence.

The strict consensus contains 59, 17 and 44 edges for P12, P13 and P23. Construction-held-out molecular edge-distance reductions are '''+pct(ee)+r'''. At q25, matched-target overlap-defect reductions are '''+pct(co)+r'''. Conditioning on exact endpoint populations and degree margins, source-error reductions are '''+pct(fi)+r'''. Both aggregate and weakest-component family statistics pass the frozen criterion. The adjusted O1 fidelity component remains unsupported (maxT tail '''+num(fi[0]['maxT_tail'])+r'''); family support is not a claim of universal marginal support.

All three source-domain overlaps and their weakest-component statistic are supported by the authorized S1 fixed-stratum reference on this strict object. Competitive kNN/MNN comparisons remain descriptive and support-limited. The matched molecular-effect direction persists across the tested hash, PCA32 and PCA64 representations, while finite object identity changes. Tested R0--R3 references do not reproduce the observed q25 statistics; no structural necessity, exact global correspondence or population generalization is inferred. Complete construction-feature separation resolves the feature-reuse objection within this carrier, not statistical or biological independence. Independent embryos remain necessary for confirmation.
\end{abstract}
\section{Introduction}
'''+intro+r'''
\section{Results}
\subsection{Strict reconstruction removes feature reuse, not merely shared normalization}
The v4 analysis isolated lane normalization denominators but preserved historical alternate feature assignments. Those alternate panels contained genes in the primary molecular evaluation panel. A separate denominator was therefore not sufficient to call the complete consensus construction held out. Here, the same primary gene split, projection seeds, independent per-gene 70/30 assignment semantics, q50 calibration and seven-of-nine consensus are retained, while all nine construction lanes are restricted to $G_S$ before any strict outcome is computed.

The publication-primary relation was reconstructed from nine state lanes whose complete gene union is contained in $G_S$ and disjoint from $G_R$. Geometry was frozen before $G_R$ was loaded for evaluation. The phrase ``construction-held-out molecular panel'' applies only to this strict reconstruction. Referee04 is a historical-lane sensitivity and provenance analysis, not a second publication-primary geometry. We do not retroactively relabel its results as strictly held out.

S0 is the full state panel with the primary hash projection. S1--S4 use that same full panel with four frozen alternate projections. S5--S8 apply the historical independent assignment rule to the state panel only; their sizes are 10,300, 10,307, 10,268 and 10,207 genes. They are not fixed-rank samples of exactly 10,262 genes. The historical implementation was inspected and these semantics were frozen before strict outcomes. All four full-panel perturbations and all four subpanel perturbations remain inside the same 14,660-gene union, with zero intersection with $G_R$.

The strict relation has 59/17/44 edges compared with 56/11/36 in v4. Source and target endpoint identities, edges and domains change. Identical domain cardinalities arise from within-source quantiles and do not imply identical cells. The q25 overlap sizes become 207/287/252, compared with 149/263/246 in v4. These are descriptions of different finite realizations, not landmark-count significance or annotation-selected improvements. No lane, seed, consensus threshold or panel fraction is optimized after observing $G_R$.
'''
    obj=read(ROOT/'geometry/v4_vs_strict_object_identity.csv');s+=table('Strict versus Referee04 finite object identity. Quantile domains can have equal sizes but different membership.',['Object','v4 count','Strict count','Jaccard'],[(r['object']+' '+(r['pair'] or r['orientation'] or r['overlap']),r['reference_count'],r['strict_count'],num(r['Jaccard'])) for r in obj if r['object']!='domain' or r['scale']=='q25'])
    s+=fig(1,'Strict feature separation and finite-object change. All nine construction gene sets are contained in $G_S$, their union has zero $G_R$ intersection, and state-only strict geometry changes endpoint, edge and domain identities. Jaccards compare different objects on the same cell carrier; they are not replication statistics.')
    s+=r'''\subsection{Construction-held-out landmark edges retain molecular agreement}
Within each embryo pair, observed strict edges are compared with fresh IID matched cross-pair edges preserving their frozen post-construction coarse-state-pair and state-distance-decile histogram. Annotations enter this reference matching only after the construction object has been sealed. They did not select the relation. The three mean molecular edge distances are lower than the corresponding reference means by '''+pct(ee)+r'''. The raw and maxT-adjusted component tails, as well as the aggregate and minimum family tails, are at the finite-reference resolution floor $1/1025$. These are conditional edge-agreement results, not evidence that the selected edge counts themselves are enriched or significant.

\subsection{Matched target neighborhoods remain coherent in the molecular panel}
For each frozen source cell, independently sampled target subsets preserve native fiber cardinality and the specified target coarse-state/distance-decile histogram. State target means are unit normalized; molecular target means are not re-normalized after averaging. Overlap defect compares the target means supplied by the two outward pair systems on the same overlap source cell. All three held-out relative reductions are positive, '''+pct(co)+r''', with adjusted component, aggregate and weakest-component support. Matched state reductions are '''+pct(sc)+r'''. The q10 and q50 replays are sensitivities, not outcome-selected substitutes for q25.

\subsection{Degree-controlled connectivity retains modest source information}
The degree-only reference fixes exact source and target endpoint populations and both degree margins, while randomizing simple bipartite connectivity. It imposes no coarse-state or distance restriction. The observed geometry's anchors, active-anchor neighborhoods and source domains remain fixed; only each accepted graph's induced target fibers and means are recomputed. Thus this test asks what remains when the marginal populations and their connectivity multiplicities cannot change.

Held-out source-error reductions are '''+pct(fi)+r'''; state reductions are '''+pct(sf)+r'''. The strict held-out aggregate statistic is $T_{\rm sum}=$'''+num(fid['T_sum'])+r''' and the weakest statistic is $T_{\rm min}=$'''+num(fid['T_min'])+r''', both with tails $1/1025$. The exact observed errors, reference means, reference sample SDs, raw and adjusted component tails are shown below. O1 has a positive reduction and raw tail below .05, but its maxT-adjusted tail is '''+num(fi[0]['maxT_tail'])+r''' and does not pass the marginal .05 criterion. O2 and O3 remain individually adjusted-supported. All three positive directions plus supported sum and minimum satisfy the separately frozen primary family success definition; that definition does not require all three marginal maxT tests to pass.
'''
    for title,rr in [('Construction-held-out edge agreement',ee),('Matched construction-held-out coherence at q25',co),('Degree-controlled construction-held-out source fidelity at q25',fi),('Degree-controlled state source fidelity at q25',sf)]:s+=table(title+'. SD describes null draws, not biological replicate uncertainty.',['Object','Observed','Null mean','Null SD','Reduction','Raw tail','maxT tail'],[(r['component'],num(r['observed']),num(r['null_mean']),num(r['null_sd']),num(r['relative_effect']),num(r['conditional_tail']),num(r['maxT_tail'])) for r in rr])
    s+=r'''\subsection{Aggregate, weakest-component and marginal tests answer different questions}
For each synchronized three-component reference draw, standardized improvement uses the fixed null component mean and sample SD. The sum test compares the observed sum with null sums. The minimum test compares the observed weakest improvement with the null minimum. In contrast, a maxT-adjusted marginal test compares each observed standardized improvement with the null maximum. Consequently, a modest positive weakest component can be unusual relative to null minima while not being unusual relative to null maxima. There is no contradiction and no authority to convert the minimum-family result into universal marginal support. The manuscript retains this distinction for the unsupported O1 molecular fidelity component.
'''+fig(2,'Strict construction-held-out molecular validation. Bars show observed error/defect versus conditional-reference means; whiskers are reference-draw sample SD, not embryo-level confidence intervals. All three primary families pass their frozen sum/minimum criteria. Degree-controlled O1 marginal maxT is unsupported; the weakest-family statistic tests a different rejection event.')
    s+=r'''\subsection{Spatial overlap is supported on the new strict object}
The authorized S1 reference preserves coarse state, local density, radial position and nearest-neighbor strata fixed once from the sealed state geometry. Each draw selects fresh matched anchors without replacement and refits its q25 source radius by the same rule as the observation. Observed overlaps of 207/287/252 cells exceed reference means of '''+', '.join(num(r['null_mean']) for r in spatial)+r'''. All three maxT tails and the aggregate/minimum tails are at $1/1025$. In contrast to the v4 object, O1 and the weakest family now gain support. This is an authorized reconstruction-dependent change, not revival of original-spatial or S2 programs. The original spatial reference is not replayed here.

\subsection{Developmental composition remains descriptive}
After all construction outputs are sealed, cell-type, germ-layer, coarse-state and cell-cycle annotations describe each pair's source, target and combined endpoint population, and the three overlap populations. The pair descriptions below are combined endpoints; separate side-specific counts and full category fractions are in the companion. O1 is more strongly mesodermal than O2 or O3; the latter remain mixed. Phase is reported explicitly and is not a hidden construction input. Neither developmental annotation nor phase fractions imply enrichment, lineage direction, mechanism or causal authority.
'''
    bio=read(ROOT/'biology/object_composition_comparison.csv');s+=table('Dominant germ-layer and phase categories on the strict object; fractions are descriptive.',['Object','Germ layer','Fraction','Phase','Fraction'],[(o,next(r['isolated_dominant'] for r in bio if r['object']==o and r['field']=='germLayer'),num(next(r['isolated_fraction'] for r in bio if r['object']==o and r['field']=='germLayer')),next(r['isolated_dominant'] for r in bio if r['object']==o and r['field']=='phase'),num(next(r['isolated_fraction'] for r in bio if r['object']==o and r['field']=='phase'))) for o in ('P12','P13','P23','O1','O2','O3')]);s+=fig(3,'Strict spatial and biological geometry. S1 distributions contain 1,024 direct IID draws. Germ-layer fractions describe the selected finite populations only; there is no annotation enrichment or causal test.')
    s+=r'''\subsection{Competitive baselines delimit, rather than establish, specificity}
Matched-size kNN uses exactly the native fiber size for each source cell. MNN5 defines reciprocal five-nearest-neighbor target sets and reports its native support separately from the common support. Fixed-size MNN5 is evaluated only where native MNN degree is at least the strict fiber size; the nearest such MNN targets supply exactly that size. Its eligibility and coverage are explicit, rather than filled with manufactured observations. In the q25 overlap comparisons, state-space native errors are higher than all three corresponding baseline errors. Matched-size kNN molecular comparisons are mixed. Native and fixed-size MNN5 have higher molecular errors than strict fibers on their respective common eligible supports. These paired finite-carrier differences are descriptive, not population p-values or proof of a privileged integration algorithm. Per-source mean and median errors, fiber sizes, support and eligibility accompany every orientation and scale.
'''
    base=read(ROOT/'baselines/comparison.csv');s+=table('q25 paired overlap error differences (native minus baseline). Negative values favor native; supports differ by baseline.',['Baseline/panel','O1','O2','O3'],[(b+' / '+p,*[num(next(r['paired_difference_mean'] for r in base if r['baseline']==b and r['panel']==p and r['scale']=='q25' and r['orientation']==o)) for o in ('O1','O2','O3')]) for b in ('matched_knn','mnn_k5','mnn_fixed_size') for p in ('state','heldout')]);s+=fig(4,'Competitive baselines on declared common support. Native-minus-baseline differences are descriptive. Native MNN5 support and fixed-size eligibility are not interchangeable; no missing source cell is assigned an artificial result.')
    s+=r'''\subsection{Tested effect direction persists while finite realization changes}
PCA32 and PCA64 controls reuse byte-verified state-panel-only isolated expression and PCA authorities. Their q50 single-lane relations are controls, not replacement consensuses selected to improve molecular outcomes. A single-lane primary hash comparison provides a like-for-like construction control, and comparison with the strict nine-lane primary is separately labeled. The target-PCA32 sensitivity changes the molecular representation while leaving the strict hash geometry unchanged. All matched state and molecular defect directions remain positive and individually adjusted-supported in these tested controls. Endpoint, edge, domain and overlap memberships change; object equality is not established.

The effect direction is more stable across the tested representations than the identity of the finite objects that realize it. This sentence concerns exactly the tested constructions. It is not an assertion about every finite representation, a representation-free biological identity, or independent replication across carriers.
'''
    rr=read(ROOT/'representation/effect_direction.csv');s+=table('Matched relative reductions in the tested representations at q25.',['Representation/panel','O1','O2','O3'],[(r['representation']+' / '+r['panel'],*[num(v) for v in r['reductions'].split('|')]) for r in rr]);s+=fig(5,'Matched molecular direction in strict hash and PCA state controls, alongside object Jaccards. Strict-consensus versus single-lane PCA identity is distinct from the separately exported like-for-like primary-hash versus PCA control. No universal representation-invariance claim is made.')
    s+=r'''\subsection{Tested R0--R3 references do not reproduce q25 observations}
R0 samples fixed-size target sets from the complete target embryo. R1 conditions on the exact target endpoint population. R2 additionally preserves the sourcewise coarse-state/distance histogram. R3 conditions that law on coverage of the entire fixed target endpoint population. Fresh independent draws, with explicit whole-draw rejection for the R3 coverage condition, replace finite chains. For state and molecular defect and source error, each tested reference's sum and minimum tail is at $1/1025$. Thus those tested reference families do not reproduce the observation. This does not establish minimal information, structural necessity, ownership, higher R4/R5 conclusions or any untested reference law.

\subsection{Terminal claim boundaries are not repaired by relabeling}
The strict construction and all three frozen primary molecular families establish construction-held-out validation within the measured carrier. Historical partially reused molecular features do not support this primary result. There is no failed-chain reference, early stopping, additional split or post-outcome tuning. Count significance, broad/local composition enrichment, bridge/common-refinement enrichment, R4/R5, strict ownership and S2 remain closed. Exact descent and global equivalence remain outside the supported authority. Historical-object counterexamples are not silently promoted to new-object theorems; no new strict exact/global theorem is asserted here.
'''+fig(6,'Final within-carrier authority. R0--R3 entries describe the tested conditional laws only. The retained molecular signature, descriptive biology and unsupported exact/global or ownership claims remain explicitly distinct. Reference draws do not increase the number of biological embryos.')
    s+=r'''\clearpage
\section{Discussion}
The strict revision addresses a specific source of circularity: a disjoint primary split was insufficient when alternate construction lanes reused primary evaluation genes. Removing that reuse requires restricting the entire construction bank, not only its nominal main coordinate. The final gene union and executable construction boundary now supply that stronger authority. The historical lane assignment semantics are preserved within $G_S$, so the revision does not substitute a new outcome-selected grammar.

The resulting molecular findings are not numerically invariant. Edge reduction magnitudes decrease in all three embryo pairs relative to v4. Matched coherence strengthens in O1 and O3 and weakens in O2. All degree-controlled fidelity reduction magnitudes increase, while O1's marginal adjusted evidence weakens. The strict primary therefore survives with measured magnitude dependence and a narrower component statement, rather than through the fiction that every earlier finite object or significance claim is unchanged.

Conditioning on endpoint populations and exact degrees is especially useful because it separates connectivity information from merely selecting favorable cells or favorable multiplicities. The remaining held-out fidelity advantage is modest, around two to four percent, and must be presented with its complete reference distributions. The supported family result does not erase the unsupported O1 marginal comparison. It also does not prove a causal mechanism, a privileged alignment algorithm or a necessity theorem for the chosen construction.

The overlap pattern and developmental compositions give the geometry interpretable content. The same local source cell can participate in different pair-specific neighborhoods, without requiring those neighborhoods to descend to a unique common state. Strong S1 support on the strict object shows that the changed relation selects an unusual overlap arrangement relative to that particular fixed-stratum law. Composition describes which observed cells supply it; it does not convert those labels into selection criteria or biological explanations.

Finally, stability of a conditional effect direction and stability of finite identity are distinct. The tested controls preserve the matched molecular direction despite changes in finite membership. The useful object is an auditable local relation-valued realization, not a unique carrier-independent finite biological partition. This paper closes that within-carrier question without beginning a new horizon, recurrence or Paper4 program.

\section{Scope and limitations}
'''+LIMITATION.replace('independent embryos',r'\linebreak[4]\mbox{independent embryos}')+r'''

The three E7.5 embryos are the biological units. The 1,024 reference draws per frozen bank are conditional randomizations of one measured carrier, not 1,024 independent biological samples. This referee-stage freeze precedes its new strict outcomes but is not an independent replication of the research program. Within-carrier conditional tails must not be presented as population confidence or independent external confirmation.

Construction-feature separation means that no $G_R$ count or identity is used by any numerical construction lane. It does not imply statistical independence of gene expression in the same cells, biological independence of measurements, absence of all measurement error, or causal separation of pathways. The strict graph was not selected by its held-out performance, but its inferential hierarchy was developed on the same carrier. Null-draw SDs quantify reference dispersion only.

Competitive comparisons use declared common support. Native MNN5 and fixed-size MNN do not have the same admissible cells; superior error on one eligible population is not a universally superior estimator. Alternate representation controls, quantile sensitivities and historical-lane comparisons remain subordinate to the unique strict q25 primary. No failed primary result is substituted with one of them.

The exact/global and higher ownership programs remain outside this paper's established authority. No count or annotation significance is inferred from the final pair populations. No external data, later stage, temporal recurrence or cross-horizon experiment is introduced in this revision.

\section{Methods}
\subsection{Data, cell identity and frozen gene panels}
The source is MELA v1, Zenodo record 10.5281/zenodo.19892785, with the same three E7.5 source files and 3,704 lineage-qualified cells as the inherited analysis \cite{Colgan2026}. Replicate counts are 1,032, 1,298 and 1,374. The ordered primary gene partition remains byte-identical: $|G_S|=14,660$, $|G_R|=6,339$, and $G_S\cap G_R=\varnothing$. Derived selected-count and identity inputs, hashes and provenance are supplied in the review companion. Full raw third-party carriers are not redistributed or relabeled as new samples.

\subsection{Frozen lane rules and restricted Stage A}
Each lane uses $\log(1+10^4 x_g/\sum_{h\in G_{\rm lane}}x_h)$. A zero selected library maps to a zero row, rather than introducing an infinite factor. Hash buckets and signs use the frozen projection seed and gene identity; the primary lane preserves the historical float32 storage followed by float64 unit normalization, while perturbation lanes use float64. The subpanel inclusion rule is the historical first-64-bit SHA256 value of seed plus gene identity, modulo ten less than seven, restricted to $G_S$. No full-cell or $G_R$ count enters any lane denominator.

Stage A receives only selected $G_S$ raw counts, ordered $G_S$ identities/indices, cell hashes and embryo identities, and frozen seeds/constants. It reads neither $G_R$ raw counts nor molecular coordinates, annotations, phase, lineage/history or evaluation statistics. Both Python file-opening interfaces are instrumented against an exact input allowlist; the numerical compute function has no parent or evaluation imports. Plan and complete strict geometry are separately committed before the Stage B reveal receipt.

Preparation of the restricted input and the independent poison auditor operate outside that numerical boundary. They can read the historical complete selected-count carrier; this access is explicitly recorded rather than attributed to Stage A. The adversarial auditor replaces all stored $G_R$ count values with a deterministic nonnegative pseudorandom source while preserving $G_S$ bytes, re-executes the actual construction function, and compares all 219 numerical-array digests and the entire compressed geometry byte stream. All are identical. This is a computational noninterference test, not biological evidence.

\subsection{Finite relational geometry}
'''+defs+r'''
\subsection{Construction guarantees and geometry freeze}
Lane relations use the q50 quantile of the pooled directional nearest cross-embryo state distances. The final pair relation consists of exactly those edges supported by at least seven of nine lanes. Source anchor sets, distances, q10/q25/q50 radii, active anchors, target fibers, domains and overlaps are exported before molecular coordinates are loaded. Nonempty fibers follow from the construction's active-anchor incidence and are audited; they are not independently tested as a scientific enrichment. The publication primary is q25, with other scales labeled as sensitivities.

\subsection{Reference laws and statistics}
All retained banks contain $B=1024$ fresh direct IID draws with independent deterministic seed addresses and no early stopping. The edge law preserves post-construction coarse-state-pair and state-distance-decile edge histograms. Matched-target laws preserve sourcewise target cardinality and coarse-state/distance histograms. S1 uses covariate strata fixed once from the sealed geometry; its landmarks are matched within those strata and each radius is refitted by the observed rule. R0--R3 use the explicitly declared target-subset laws; there is no R4/R5 replay or switch-chain approximation.

For component $i$, standardized improvement is
\[
Z_i=\frac{s(T_i^{\rm obs}-\overline T_i^{\rm null})}{s_i^{\rm null}+10^{-8}},\qquad
s=-1\text{ for error/defect},\quad s=+1\text{ for overlap size}.
\]
Reference SD uses the sample denominator $B-1$. Synchronized draw vectors define $T_{\rm sum}=\sum_i Z_i$ and $T_{\rm min}=\min_i Z_i$. A $+1$ exceedance correction gives $(1+\#\{b:T_b\ge T_{\rm obs}\})/(B+1)$ and resolution floor $1/1025$. Component maxT tails use the drawwise maximum; the minimum-family tail uses the drawwise minimum. Thresholds are fixed at .05. Each primary molecular family succeeds only when all three relative reductions are positive and both sum and minimum tails are at most .05. Marginal maxT support is reported separately.

\subsection{Exact degree-only IID sampling and rejection transparency}
Each degree-only graph is drawn from a fresh independent uniformly permuted labeled target-stub pairing with the fixed source stubs. Nonsimple proposals are discarded completely and resampled until simplicity. All simple graphs with the fixed margins have identical labeled-pairing multiplicity, $\prod_u d_u!\prod_v d_v!$, so conditioning induces the uniform simple-graph law. No chain, state stratum or distance constraint is used. Pair graphs are sampled independently, synchronized into complete draw vectors, and shared across the three scale sensitivities. Every attempt count, seed and accepted graph hash is retained. The resulting simplicity acceptance and maximum attempts are shown below; acceptance is a measured computational rate, not biological support.
'''
    s+=table('Degree-only sampling transparency. Every pair has exactly1,024 accepted IID simple graphs.',['Pair','All attempts','Rejected','Acceptance','Mean attempts','Median','Maximum'],[(r['pair'],r['attempted_stub_pairings'],r['rejected_nonsimple'],num(r['acceptance_fraction']),num(r['mean_proposals_per_accepted']),r['median_proposals_per_accepted'],r['maximum_proposals']) for r in sampler])
    s+=r'''\subsection{Controls, descriptive annotation and complete verification}
Matched-size kNN and reciprocal MNN5 are computed in the declared state representation with deterministic tie ordering. Fixed-size MNN uses the same frozen eligibility rule, not a post-outcome change of $k$. Every orientation and q10/q25/q50 support table is supplied. PCA32/PCA64 state and target-PCA32 authorities are reused only after their feature provenance, means, scores, loading orthogonality, signs and eigenpair residuals have been checked. Their single-lane geometry is rechecked independently.

Cell type, germ layer, coarse state and phase are loaded only after construction and are used for descriptive fractions or authorized post-construction matching. No annotation-based causal claim is tested. The complete verifier reconstructs strict lane counts, normalization, all finite geometry, every retained reference graph and statistic, baseline source cells and annotation fractions. It checks all 95 terminal answers, the twenty-claim matrix, six source-backed figures and the rendered manuscript. The standalone package contains ordinary files and required derived inputs; it does not require Git, private paths, raw-H5TD acquisition, credentials, Lean rebuilding or a compiler.

\section{Data availability}
Source data remain at the official MELA archive cited above. The companion contains the unchanged partition, selected derived $G_S$ count matrix, post-reveal panel-isolated expression and projection authorities, cell identities, strict geometry, reference tables and provenance. Source attribution and third-party rights are preserved; no blanket relicensing of those data is asserted. Re-extraction from full external raw carriers is distinct from replay of the supplied derived input.

\section{Code availability}
The paper-specific local review companion is the supplied Referee05 reviewer release. Run \texttt{python verify\_release.py} with the listed numerical dependencies. The manifest, graph seeds, all conditional statistics, degree attempt logs and validation receipts are included, together with this rendered PDF, source TeX, six figure PDFs, previews and source CSVs. This package is a review handoff, not an assertion that an external public release has already occurred. The broader development repository and other agents' work are outside its scope.

\section{Author contributions}
'''+admin+r'''
\clearpage
\appendix
\section{Frozen within-carrier conditional inference map}
The strict relation is the only publication-primary construction. Edge agreement, matched coherence and degree-controlled fidelity satisfy their frozen molecular family criteria. S1 aggregate and weakest-component evidence also survive. R0--R3 remain tested-reference nonreproduction, not necessity. Baselines and biological fractions are descriptive. The O1 molecular fidelity marginal maxT result remains unsupported despite the supported minimum-family statistic. Historical Referee04 is sensitivity/provenance only. No positive claim relies on reused evaluation features or a failed-chain reference.

\section{Final claim matrix}
\begin{longtable}{p{.07\textwidth}p{.31\textwidth}p{.53\textwidth}}
\toprule Code & Claim & Final typed status \\ \midrule
'''
    for r in read(ROOT/'completion/claim_matrix.csv'):s+=esc(r['claim'])+' & '+esc(r['title'])+' & '+esc(r['status']).replace(r'\_',r'\_\allowbreak{}')+r' \\'+'\n'
    s+=r'''\bottomrule\end{longtable}
\section{Bibliography}
'''+bib+'\n\\end{document}\n';s=s.replace('Polański',r"Pola\'nski").replace(r'\texttt{research/rmmo\_paper3\_referee05/reviewer\_release/}',r'\texttt{research/}\allowbreak{}\texttt{rmmo\_paper3\_referee05/}\allowbreak{}\texttt{reviewer\_release/}');md('manuscript_authority/Paper3_v5.tex',s)
    js('manuscript_authority/revision_receipt.json',{'original_v4_sha256':sha(ROOT/'manuscript_authority/Paper3_v4_original.tex'),'new_tex_sha256':sha(ROOT/'manuscript_authority/Paper3_v5.tex'),'results_methods_discussion_rewritten_against_strict_authorities':True,'original_intro_related_work_admin_bibliography_retained':True,'original_download_file_modified':False,'new_external_literature_search':False,'unique_primary':'strict GS-only consensus','six_actual_figures':True})
    print('Actual Paper3 v5 source generated from suppliedv4 plus strict numerical authorities',flush=True)
def receipt():
    f=ROOT/'manuscript_authority';log=(f/'Paper3_v5.log').read_text();assert 'Output written on' in log or (f/'Paper3_v5.pdf').stat().st_size>100000;assert 'undefined references' not in log.lower() and 'undefined citations' not in log.lower();js('manuscript_authority/render_receipt.json',{'original_v4_sha256':sha(f/'Paper3_v4_original.tex'),'tex_sha256':sha(f/'Paper3_v5.tex'),'pdf_sha256':sha(f/'Paper3_v5.pdf'),'compiler':'tectonic0.17 warm cached bundle; --only-cached --untrusted','figure_sha256':{f'figures/figure{i:02}.pdf':sha(ROOT/f'figures/figure{i:02}.pdf') for i in range(1,7)},'rendered_utc':utc(),'unresolved_references':False})
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('action',choices=['build','receipt']);globals()[p.parse_args().action]()
